var bible_chapter = [];
bible_chapter.push("1 한나의서원, 사무엘출생");
bible_chapter.push("2 한나의 기도 홉니와비느하스");
bible_chapter.push("3 사무엘의소명");
bible_chapter.push("4 에벤에셀 법궤탈취 엘리 멸망");
bible_chapter.push("5 아스돗 / 가드, 에그론 / 법궤 옮김");
bible_chapter.push("6 벧세메스로 가는 소");
bible_chapter.push("7 아비나답 집의법궤 미스바대성회");
bible_chapter.push("8 왕을구함");
bible_chapter.push("9 사울등장");
bible_chapter.push("10 행구 뒤에 숨은 사울");
bible_chapter.push("11 왕으로 즉위 하는 사울");
bible_chapter.push("12 사무엘이 사울에게 나라를 맡김");
bible_chapter.push("13 사울의 제사장직 월권");
bible_chapter.push("14 사울왕의 금식명령");
bible_chapter.push("15 여호와께서 왕을 버리심");
bible_chapter.push("16 다윗의 기름부음");
bible_chapter.push("17 골리앗과 다윗");
bible_chapter.push("18 다윗의 승리 요나단의사랑");
bible_chapter.push("19 다윗의 피신 라마나욧");
bible_chapter.push("20 요나단의 화살신호");
bible_chapter.push("21 놉땅으로피신 가드피신");
bible_chapter.push("22 아둘람굴 모압의미스베 유다헤렛수풀");
bible_chapter.push("23 그일라 십황무지 요나단과상면");
bible_chapter.push("24 사울살려줌1 엔게디요새");
bible_chapter.push("25 바란광야 마온피신 아비가일");
bible_chapter.push("27 블레셋으로 가드,시글락");
bible_chapter.push("26 십광야 하길라산피신 사울살려줌2");
bible_chapter.push("28 사무엘초혼");
bible_chapter.push("29 다윗을불신임 하는 블레셋");
bible_chapter.push("30 아말렉에게약탈당한 시글락");
bible_chapter.push("31 사울왕가 멸망");

var comment = [];
comment.push('<사무엘 상서의 파노라마>');
comment.push('   1.사무엘 가정의 이야기');
comment.push('   2.엘리 가정의 이야기');
comment.push('   3.왕을 구하는 이스라엘');
comment.push('   4.사울 왕의 등극과 실수');
comment.push('   5.다윗의 젊은 시절');
comment.push('   6.다윗의 망명생활');
comment.push('   7.사울 왕가의 몰락');
comment.push("<img src='./img/1_Samuel_01.png'>");
comment.push("<img src='./img/1_Samuel_02.png'>");