var bible_chapter = [];
bible_chapter.push("1 아하시아의병");
bible_chapter.push("2 엘리야승천 엘리사사역 ");
bible_chapter.push("3 엘리사의감동여호람왕");
bible_chapter.push("4 과부의기름수넴여인");
bible_chapter.push("5 문둥병자나아만치료한엘리사");
bible_chapter.push("6 벤하닷의사마리아포위");
bible_chapter.push("7 하나님의군대 소리로도망친벤하닷");
bible_chapter.push("8 요람의부상아하시아의방문");
bible_chapter.push("9 예후의반역과이세벨죽음");
bible_chapter.push("10 예후의명령에아합아들 70명죽음");
bible_chapter.push("11 아달랴의반역여호야다혁명");
bible_chapter.push("12 요아스성전수리");
bible_chapter.push("13 엘리사죽음과뼈회생[요나서]");
bible_chapter.push("14 아마샤가요아스에게선전포고");
bible_chapter.push("15 [암,호,욜]아사랴왕의문둥병");
bible_chapter.push("16 아하스와베가의전쟁[사,미,나,옵]");
bible_chapter.push("17 북이스라엘멸망");
bible_chapter.push("18 히스기야때 앗수르 산헤립 침공");
bible_chapter.push("19 이사야 예언성취");
bible_chapter.push("20 히스기야목숨연장");
bible_chapter.push("21 므낫세,아몬우상숭배");
bible_chapter.push("22 요시야왕 율법책발견");
bible_chapter.push("23 요시야왕종교개혁[합,습,렘]");
bible_chapter.push("24 느브갓네살 1,2차 침입");
bible_chapter.push("25 느브갓네살3차 침입[렘,애가]");

var comment = [];
comment.push("1~10장 북IS 사건들");
comment.push("11~17장 남북 사건");
comment.push("18~25장 남유다사건들");
comment.push("<열왕기 하서의 파노라마>");
comment.push("엘리야의 승천과 엘리사의 사역");
comment.push("하나님은 구원이시라");
comment.push("오므리 왕조의 몰락과 예후 왕조");
comment.push("예후의 열심과 통치");
comment.push("남쪽의 악녀 아달랴");
comment.push("엘리사의 죽음과 요나의 소명");
