var bible_chapter = [];
bible_chapter.push("1사울죽음과 다윗의슬픔 활 노래");
bible_chapter.push("2 아브넬과 요압의대결 다윗왕 즉위");
bible_chapter.push("3 아브넬의망명");
bible_chapter.push("4 암살당한 이스보셋 다윗의슬픔");
bible_chapter.push("5 통일왕국 다윗왕 즉위 ");
bible_chapter.push("6 법궤입성/춤추는다윗/미갈의비방");
bible_chapter.push("7 다윗의 성전건축계획 허락하지않음");
bible_chapter.push("8 다윗의 통치조직");
bible_chapter.push("9 므비보셋을 선대하는 다윗");
bible_chapter.push("10 다윗신하 암몬에게 수치를당함 ");
bible_chapter.push("11 다윗과밧세바");
bible_chapter.push("12 다윗을 책망한 나단");
bible_chapter.push("13 암논이 누이 다말을 강간함");
bible_chapter.push("14 도망쳤던 압살롬의  귀환");
bible_chapter.push("15 압살롬의반역 다윗의 피신");
bible_chapter.push("16 압살롬이 예루살렘점령 후새의 환대");
bible_chapter.push("17 후새의모략 다윗피신");
bible_chapter.push("18 압살롬의죽음");
bible_chapter.push("19 다윗의 슬픔");
bible_chapter.push("20 세바의반란");
bible_chapter.push("21 블레셋물리친 4명의용사");
bible_chapter.push("22 다윗의찬양시 시편18편");
bible_chapter.push("23 다윗의용사들");
bible_chapter.push("24 인구조사와 온역재앙");

var comment = [];
comment.push('<사무엘 하서의 파노라마>');
comment.push('');
comment.push('1.다윗의 집과 이스보셋의 세력다툼');
comment.push('2.아브넬과 이스보셋의 죽음');
comment.push('3.다윗의 통일 왕국');
comment.push('4.언약궤의 안치');
comment.push('5.다윗의 승승장구');
comment.push('6.다윗의 범죄와 하나님의 징계');
comment.push('7.압살롬의 반역');
comment.push('8.압살롬의 난 평정');
comment.push('9.다윗의 인구 조사');
