var bible_chapter= [];

bible_chapter.push('1 예수님의승천 마가다락방');
bible_chapter.push('2 초대교회 오순절성령강림 베드로의 설교');
bible_chapter.push('3 미문의 앉은뱅이 고침');
bible_chapter.push('4 초대교회 베드로의공회');
bible_chapter.push('5 아나니아와 삽비라');
bible_chapter.push('6 일곱 집사 선출');
bible_chapter.push('7 스데반의 순교');
bible_chapter.push('8 사울의 박해');
bible_chapter.push('9 사울의 다메섹 도상의 회개');
bible_chapter.push('10 베드로의 환상');
bible_chapter.push('11 안디옥교회 설립과 최초로 그리스도인 칭함');
bible_chapter.push('12 베드로 감옥 탈출과 헤롯의 죽음');
bible_chapter.push('13 제1차 전도여행 출발');
bible_chapter.push('14 바울이 앉은뱅이고침(루스드라성)');
bible_chapter.push('15 Jer총회 제2차 전도 여행출발');
bible_chapter.push('16 빌립보 감옥에갇혔을 때 간수전도');
bible_chapter.push('17 베회아 전도 아덴 전도');
bible_chapter.push('18 장막일 /제3차 전도여행 살전후, 갈');
bible_chapter.push('19 믿을때에 성령받았느냐 고전후');
bible_chapter.push('20 로마서 바울의 고별 설교');
bible_chapter.push('21 Jer도착 붙잡힌 바울');
bible_chapter.push('22 바울의 변론');
bible_chapter.push('23 바울 살해 조직단 결성');
bible_chapter.push('24 벨릭스 총독앞에 선 바울(가이사랴)');
bible_chapter.push('25 베스도 총독앞에 선 바울(가이사랴)');
bible_chapter.push('26 아그립바 왕 앞에 선 바울(가이사랴)');
bible_chapter.push('27 배가 광풍에 고생함(유라굴로광풍)');
bible_chapter.push('28 바울의 로마 감옥 생활 엡,골,몬,빌');

var comment= [];
comment.push('1~12장 예루살렘 베드로 중심');
comment.push('13~28장 안디옥 바울 중심');
comment.push('<연대기 순으로 재배열 한 책>');
comment.push('18:11 - 살전후,갈라디아서');
comment.push('19:20 - 고전후');
comment.push('20:3  - 로마서');
comment.push('28:31 - 엡,골,몬,빌');
comment.push('[사도들의 발자취를 따라서]');
comment.push('▸사도행적은 누가복음의 속편처럼 기록되었다.');
comment.push('▸사도들의 행적 전체를 다 기록한 것이 아니라 베르로 행적과 야고보 순교 스테반 순교 그리고 바나바와 바울 행적을 다루고 있다.');
comment.push('▸복음이 예루살렘과 온 유대와 사마리아와 온 땅으로 어떻게 전파되고 확산되어갔는지, 그리고 어떻게 로마에까지 복음이 전해졌는지를 밝히고 있다.');
comment.push('▸사도행적은 일대 전환의 책이다. 예수님의 시대에서 사도들의 시대로, 복음이 유대에서 이방인들의 세계로 전파된 역사를 기록하고 있다.');
comment.push('');
comment.push('▸사도 바울의 회심과 소명을 바여준다.');
comment.push('▸바나바와 바울의 협력사역을 보여준다.');
comment.push('▸바나바와 바울의 제 1차 전도 여행');
comment.push('▸바울과 실라의 제 2차 전도 여행');
comment.push('▸바울과 누가의 제 3차 전도 여행');
comment.push('▸바울과 누가의 로마로 가는 길을 보여준다.l');
comment.push('▸바울과 바나바 누가와 디모데 디도의 사역을 보여준다.');
comment.push('▸바울의 서신 10편이 어떻게 기록되었는지를 보여준다. [재구성]');
comment.push('▸선교의 명령과 선교의 모범과 역사를 기록했다.');