var bible_chapter = [];
bible_chapter.push("1 1차 설교출애굽40년");
bible_chapter.push("2 헤스본 정복롯의 자손땅");
bible_chapter.push("3 가나안 땅을바라보는모세");
bible_chapter.push("4 2차 설교모압평지");
bible_chapter.push("5 십계명");
bible_chapter.push("6 쉐마이스라엘6:5");
bible_chapter.push("7 가나안우상타파(7족진멸)");
bible_chapter.push("8 광야교훈");
bible_chapter.push("9 깨진두돌판(금송아지)");
bible_chapter.push("10 새 돌판");
bible_chapter.push("11 이른 비늦은 비");
bible_chapter.push("12 우상제거명령");
bible_chapter.push("13 거짓선지자죽이라");
bible_chapter.push("14 음식 규례십일조");
bible_chapter.push("15 안식년짐승초태생");
bible_chapter.push("16 삼대 절기 ");
bible_chapter.push("17 왕정제도의주의할 사항");
bible_chapter.push("18 제사장선지자");
bible_chapter.push("19 도피성제도");
bible_chapter.push("20 전쟁시유의사항");
bible_chapter.push("21 장자상속권");
bible_chapter.push("22 돌로 치는규례");
bible_chapter.push("23 배설물규례");
bible_chapter.push("24 이혼규례");
bible_chapter.push("25 태형 40대");
bible_chapter.push("26 소산맏물드림");
bible_chapter.push("27 3차 설교");
bible_chapter.push("28 축복과저주");
bible_chapter.push("29 은총회고모압언약");
bible_chapter.push("30 순종/축복생사화복");
bible_chapter.push("31 후계자여호수아");
bible_chapter.push("32 최후교훈모세의노래");
bible_chapter.push("33 12지파축복");
bible_chapter.push("34 모세의죽음");