var bible_chapter = [];
bible_chapter.push("1 헛되고헛되니 모든것이헛되도다");
bible_chapter.push("2 쾌락을얻는 사업도헛되도다");
bible_chapter.push("3 범사에때가 있고기한이 있다 ");
bible_chapter.push("4 해아래서헛된 것을보았도다");
bible_chapter.push("5 아무것도손에 가지고가지못하리라");
bible_chapter.push("6 식욕(욕망)은 차지아니하느니라");
bible_chapter.push("7 초상집이잔치집 보다배울것이많다");
bible_chapter.push("8 악행자,선행자 모두 죽으니헛되다");
bible_chapter.push("9 산 개가죽은 사자보다 낫다");
bible_chapter.push("10 합정을파는 자는거기빠지리라");
bible_chapter.push("11 청년의때를주안에서뜻있게보내라");
bible_chapter.push("12 늙기전에창조자를기억하라 ");
var comment = [];
comment.push("<전도서의 파노라마>");
comment.push("▸전도서는 솔로몬의 인생론 즉 철학이다.");
comment.push("▸전도서의 핵심은 하나님의 떠나서 세상에서 추구하는 모든 것은 다 헛되다는 것이다.");
comment.push("▸사람들이 중히 여기는 부귀 영화 명예 권세지혜와 지식이 다 사람을 번뇌하게 할 뿐이었다.");
comment.push("▸사람이 해아래서 가족이 화목하고 하나님의 명령을 지키는 것이 사람의 본분이요 분복이라는 사실을 깨닫게 되었다.");
comment.push("▸최후에는 하나님의 심판이 있다는 것을 기억하자.");