var bible_chapter = [];
bible_chapter.push("1 IS.고역");
bible_chapter.push("2 모세출생");
bible_chapter.push("3 떨기나무");
bible_chapter.push("4 모세의 지팡이");
bible_chapter.push("5 내백성을 보내라!");
bible_chapter.push("6 언약확인");
bible_chapter.push("7 피 재앙");
bible_chapter.push("8 개구리, 이, 파리");
bible_chapter.push("9 악질, 독종, 우박");
bible_chapter.push("10 메뚜기, 흑암");
bible_chapter.push("11 장자죽음예고");
bible_chapter.push("12 장자죽음 유월절 출애굽");
bible_chapter.push("13 불·구름기둥");
bible_chapter.push("14 홍해기적");
bible_chapter.push("15 모세, 미리암 찬양");
bible_chapter.push("16 만나와 메추라기");
bible_chapter.push("17 아말렉과 최초의 전쟁");
bible_chapter.push("18 장인이드로의 충고");
bible_chapter.push("19 시내산 언약");
bible_chapter.push("20 십계명");
bible_chapter.push("21 사형법");
bible_chapter.push("22 배상법");
bible_chapter.push("23 재판법");
bible_chapter.push("24 언약체결 아론과 70인 장로");
bible_chapter.push("25 법궤 만드는 법");
bible_chapter.push("26 성막 만드는 법");
bible_chapter.push("27 번제단 만드는 법");
bible_chapter.push("28 제사장 옷 만드는 법");
bible_chapter.push("29 제사장 위임법");
bible_chapter.push("30 분향단 만드는 법");
bible_chapter.push("31 증거판 (첫번째)");
bible_chapter.push("32 깨어진 증거판");
bible_chapter.push("33 모세의 중보기도");
bible_chapter.push("34 증거판 (두번째)");
bible_chapter.push("35 성막건축 예물드림");
bible_chapter.push("36 풍족한 건축예물");
bible_chapter.push("37 법궤, 진설병 상, 등, 분향단 제작");
bible_chapter.push("38 번제단, 물 두멍, 성막뜰");
bible_chapter.push("39 제사장의 의복제작");
bible_chapter.push("40 성막 봉헌식");

var comment = [];
comment.push("< 다섯 가지 신학적 주제 >");
comment.push("1.하나님의 사람준비 (1장~4장)");
comment.push("2.하나님의 자기계시 (5장~12장)");
comment.push("3.유월절 애굽(이집트) 탈출 (12장~18장)");
comment.push("4.시내산 언약	(19장~24장)");
comment.push("5.성막 건축 (25장~40장)");
comment.push("<img src='./img/Exodus.png'>");
comment.push("<img src='./img/Exodus_02.png'>");