var bible_chapter= [];

bible_chapter.push('1 제1차 귀환 (스룹바벨 인솔)');
bible_chapter.push('2 제1차 귀환 명단과 숫자 조사 (49,897명)');
bible_chapter.push('3 성전 지대 놓다. 성전 재건 시작.');
bible_chapter.push('4 사마리아인 성전 건축 반대 [학개/스가랴]');
bible_chapter.push('5 성전 건축 재개');
bible_chapter.push('6 성전 봉헌식과 유월절[에스더/역대상/하]');
bible_chapter.push('7 제2차 귀환(에스라 인솔)');
bible_chapter.push('8 제2차 귀환자명단과 숫자 조사 (1,754명)');
bible_chapter.push('9 에스라의 회개기도');
bible_chapter.push('10 이스라엘 백성들의 회개기도');

var comment= [];
comment.push('<table class="reference"><tr><th>');
comment.push('구    분</th><th>');
comment.push('연    대</th><th>');
comment.push('왕의 이름</th><th>');
comment.push('포로된 사람들</th></tr><tr><td>');
comment.push('1차 포로</td><td>');
comment.push('BC.606년</td><td>');
comment.push('여호야김</td><td>');
comment.push('다니엘 등 다수</td></tr><tr><td>');
comment.push('2차 포로</td><td>');
comment.push('BC.597년</td><td>');
comment.push('여호야긴</td><td>');
comment.push('에스겔 등 다수</td></tr><tr><td>');
comment.push('3차 포로</td><td>');
comment.push('BC.586년</td><td>');
comment.push('시드기야</td><td>');
comment.push('시드기야 외 다수</td></tr>');
comment.push('</table>');

comment.push('<table class="reference"><tr><th>');
comment.push('구    분</th><th>');
comment.push('연    대</th><th>');
comment.push('페르샤왕</th><th>');
comment.push('인솔자와 귀환자</th></tr><tr><td>');
comment.push('1차 귀환</td><td>');
comment.push('BC.536년</td><td>');
comment.push('고레스</td><td>');
comment.push('스룹바벨 외49,897명</td></tr><tr><td>');
comment.push('2차 귀환</td><td>');
comment.push('BC.457년</td><td>');
comment.push('아닥사스다</td><td>');
comment.push('에스라 외 1754명</td></tr><tr><td>');
comment.push('3차 귀환</td><td>');
comment.push('BC.444년</td><td>');
comment.push('아닥사스다</td><td>');
comment.push('느헤미야 외 다수</td></tr>');
comment.push('</table>');
