var bible_chapter = [];
bible_chapter.push("1 천지 창조");
bible_chapter.push("2 선악과 금지");
bible_chapter.push("3 유혹·타락 에덴추방");
bible_chapter.push("4 가인·아벨");
bible_chapter.push("5 아담족보");
bible_chapter.push("6 노아방주(완성)");
bible_chapter.push("7 홍수심판");
bible_chapter.push("8 아라랏산방주도착");
bible_chapter.push("9 무지개 언약");
bible_chapter.push("10 노아족보");
bible_chapter.push("11 바벨탑 인류분산");
bible_chapter.push("12 아브람의 소명");
bible_chapter.push("13 아브람·롯의 분가");
bible_chapter.push("14 살렘왕 멜기세덱");
bible_chapter.push("15 횃불 언약");
bible_chapter.push("16 이스마엘출생");
bible_chapter.push("17 아브라함의 개명,할례");
bible_chapter.push("18 의인10명");
bible_chapter.push("19 소돔 고모라 멸망");
bible_chapter.push("20 아비멜렉을 속이는 아브라함");
bible_chapter.push("21 이삭 출생");
bible_chapter.push("22 모리아산 사건");
bible_chapter.push("23 사라죽음");
bible_chapter.push("24 이삭결혼");
bible_chapter.push("25 야곱·에서 팥죽·장자");
bible_chapter.push("26 세 우물");
bible_chapter.push("27 이삭이 야곱축복");
bible_chapter.push("28 벧엘서원");
bible_chapter.push("29 레아·라헬 위한 14년");
bible_chapter.push("30 아롱진 양");
bible_chapter.push("31 야곱의 귀향");
bible_chapter.push("32 얍복강 씨름");
bible_chapter.push("33 야곱·에서 만남");
bible_chapter.push("34 디나 사건(세겜멸절)");
bible_chapter.push("35 엘벧엘");
bible_chapter.push("36 에서 족보");
bible_chapter.push("37 요셉의꿈");
bible_chapter.push("38 유다·다말");
bible_chapter.push("39 투옥된 요셉");
bible_chapter.push("40 요셉의 꿈 해몽");
bible_chapter.push("41 총리요셉");
bible_chapter.push("42 볼모가 된 시므온");
bible_chapter.push("43 베냐민을 데려오다");
bible_chapter.push("44 발견된 은잔");
bible_chapter.push("45 방성대곡");
bible_chapter.push("46 애굽에온 야곱");
bible_chapter.push("47 고센땅의 야곱가족");
bible_chapter.push("48 야곱의축북");
bible_chapter.push("49 야곱의축북");
bible_chapter.push("50 야곱장례요셉죽음");

var comment = [];
comment.push("제 1 부 : 원 역 사[1장~11장]");
comment.push("(1)하나님의 창조");
comment.push("(2)뱀의 유혹과 인간의 타락");
comment.push("(3)노아 시대 대 홍수 심판");
comment.push("(4)바벨탑 사건과 민족들의 분산");
comment.push("제 2 부 : 족장들의 신앙과 전기 [12장~50장]");
comment.push("(1)아브라함 신앙과 거룩한 생활");
comment.push("(2)이삭의 복된 생애");
comment.push("(3)야곱의 험악한 생애");
comment.push("(4)요셉의 꿈과 성취");