var bible_chapter = [];
bible_chapter.push("1 변론초청");
bible_chapter.push("2 메시아 왕국도래 예언");
bible_chapter.push("3 유다심판예언");
bible_chapter.push("4 예루살렘의영광");
bible_chapter.push("5 극상품포도들포도맺힘");
bible_chapter.push("6 나를보내소서이사야소명");
bible_chapter.push("7 처녀가잉태하여아들을 낳을것");
bible_chapter.push("8 마렐살랄하하스바스");
bible_chapter.push("9 평강의왕메시아");
bible_chapter.push("10 남은자구원사상");
bible_chapter.push("11 이새의뿌리에서한 싹이남");
bible_chapter.push("12 구원의우물들에서물길으리라");
bible_chapter.push("13 1차 바벨론멸망예언");
bible_chapter.push("14 아침의 아들계명성");
bible_chapter.push("15 모압심판예언");
bible_chapter.push("16 모압심판예언");
bible_chapter.push("17 다메섹멸망예언");
bible_chapter.push("18 구스멸망예언");
bible_chapter.push("19 애굽멸망예언");
bible_chapter.push("20 애굽,구스 멸망예언");
bible_chapter.push("21 2차 바벨론멸망");
bible_chapter.push("22 예루살렘 멸망예언");
bible_chapter.push("23 두로의 멸망예언");
bible_chapter.push("24 하나님의최후심판");
bible_chapter.push("25 심판자며구원자이신하나님께찬양");
bible_chapter.push("26 심판과구원");
bible_chapter.push("27 리워야단죽음, IS구원약속");
bible_chapter.push("28 타락한지도자심판경고");
bible_chapter.push("29 아리엘에임할 화(토기장이)");
bible_chapter.push("30 애굽을의지하는유다심판예언");
bible_chapter.push("31 애굽을의지하지말라(야훼가구원)");
bible_chapter.push("32 장차한의로운왕이통치한다");
bible_chapter.push("33 IS회복앗수르멸망예언");
bible_chapter.push("34 에돔멸망예언");
bible_chapter.push("35 택한백성IS은 회복됨");
bible_chapter.push("36 하나님께도전하는앗수르");
bible_chapter.push("37 선전에서기도하는히스기야");
bible_chapter.push("38 아하스의일영표");
bible_chapter.push("39 히스기야의실수");
bible_chapter.push("40 여호와를 앙망하라 세례요한");
bible_chapter.push("41 고레스등장");
bible_chapter.push("42 공의의종 노래");
bible_chapter.push("43 바벨론도멸하신다");
bible_chapter.push("44 고레스를쓰시는 주");
bible_chapter.push("45 고레스를 지명하심");
bible_chapter.push("46 바벨론 신벨과 느보심판");
bible_chapter.push("47 고레스에의해심판받을 바벨론");
bible_chapter.push("48 IS포로귀환약속");
bible_chapter.push("49 구원자여호와의 종");
bible_chapter.push("50 여호와의 종의 충성");
bible_chapter.push("51 Ab과사라의축복,격려");
bible_chapter.push("52 IS격려하심종의노래");
bible_chapter.push("53 메시아고난시(시 22편)");
bible_chapter.push("54 하나님의영원하신사랑");
bible_chapter.push("55 구원의 약속");
bible_chapter.push("56 이방인도구원으로초대하심");
bible_chapter.push("57 회개자를구원하심");
bible_chapter.push("58 참된 금식");
bible_chapter.push("59 선민 책망회개와용서");
bible_chapter.push("60 시온의영광일어나라!");
bible_chapter.push("61 구주사명기쁜소식");
bible_chapter.push("62 회복된시온의 영광");
bible_chapter.push("63 구원을위한이사야의중보기도");
bible_chapter.push("64 구원을위한이사야기도");
bible_chapter.push("65 새 하늘과새 땅 예언");
bible_chapter.push("66 최후 심판과구원");

var comment = [];
comment.push("1~5장 이사야의성토");
comment.push("6~12장 소명과 메시야 예언");
comment.push("13~23장 열방 심판 예언");
comment.push("24~27장 이사야 종말론");
comment.push("28~31장 경고");
comment.push("32~35장 약속");
comment.push("36~39장 히스기야 시대의 역사");
comment.push("40~48장 IS회복약속");
comment.push("49~57장 오실 메시야 약속");

comment.push("◈구조분석(때리시고 싸매시는 하나님)| 때리시는 하나님 (심판 1~39장)| 싸매시는 하나님 (위로 44~66장)");
comment.push(" <이사야 선지자의 사역>");
comment.push("▶웃시야와 요담과 아하스 히스기야 시대");
comment.push("▶이사야의 소명과 성토");
comment.push("▶메시야 시대가 온다");
comment.push("▶열방들에 대한 예언");
comment.push("▶하나님은 심판하신다");
comment.push("▶이스라엘은 회복되고");
comment.push("▶에돔은 완전히  멸망한다");
comment.push("▶히스기야 왕의 공과(功過)를 보여준다");
comment.push("▶바벨론 포로 후의 일을 기록하고 있다");
