var bible_chapter = [];
bible_chapter.push("1 욥을시험하기위해허락받는사탄");
bible_chapter.push("2 아내의조롱,세 친구방문");
bible_chapter.push("3 생일을 저주하는 욥");
bible_chapter.push("4 욥을책망하는엘리바스");
bible_chapter.push("5 계속되는엘리바스의책망");
bible_chapter.push("6 엘리바스의책망에대한욥의 답변");
bible_chapter.push("7 계속되는욥의 답변 ");
bible_chapter.push("8 빌닷의첫 번째책망");
bible_chapter.push("9 빌닷의 책망에 대한욥의 답변");
bible_chapter.push("10 계속되는욥의 답변 ");
bible_chapter.push("11 소발의첫 번째책망");
bible_chapter.push("12 소발의책망에 대한욥의 답변");
bible_chapter.push("13 욥의 답변계속");
bible_chapter.push("14 욥의 답변");
bible_chapter.push("15 엘리바스의 두 번째 책망");
bible_chapter.push("16 엘리바스의책망에대한욥의 답변");
bible_chapter.push("17 엘리바스책망에대한 욥의답변종결");
bible_chapter.push("18 빌닷의두번째 책망");
bible_chapter.push("19 빌닷의책망에 대한 욥의 답변");
bible_chapter.push("20 소발의 두번재 책망");
bible_chapter.push("21 소발의 책망에 대한 욥의 답변 ");
bible_chapter.push("22 엘리바스의 세번째 책망 ");
bible_chapter.push("23 엘리바스 의책망에대한욥의 답변");
bible_chapter.push("24 욥의 답변 계속");
bible_chapter.push("25 빌닷의세번째 책망");
bible_chapter.push("26 빌닷의 책망에 대한욥의 답변");
bible_chapter.push("27 세 친구에대한 욥의 마지막 답변");
bible_chapter.push("28 욥의마지막 답변의 계속");
bible_chapter.push("29 욥의마지막 답변의 계속");
bible_chapter.push("30 욥의마지막 답변의 계속");
bible_chapter.push("31 욥의 결백주장");
bible_chapter.push("32 엘리후의등장과 변론의 근거제시");
bible_chapter.push("33 엘리후의 1차 변론");
bible_chapter.push("34 엘리후의 2차 변론");
bible_chapter.push("35 엘리후의 3차 변론");
bible_chapter.push("36 엘리후의 4차 변론");
bible_chapter.push("37 엘리후의 4차 변론 끝");
bible_chapter.push("38 하나님의현현과 욥에게말씀하심");
bible_chapter.push("39 계속되는 하나님의말씀");
bible_chapter.push("40 욥을꾸짖는 하나님,하마의 교훈");
bible_chapter.push("41 악어사냥을 통한 인간의 한계교훈");
bible_chapter.push("42 욥의 회개중보기도,  갑절의축복");

var comment = [];
comment.push("1~3장 욥의 고난");
comment.push("4~14장 첫 번째 변론");
comment.push("15~21장 두 번째 변론");
comment.push("22~31장 세 번째 변론");
comment.push("38~41장 하나님의 말씀");
comment.push("42장 욥의 회개와 회복");
comment.push("<욥기의 파노라마>");
comment.push("▸욥기의 주제는 “의인의 고난”에 관한 문제다.");
comment.push("▸욥이 살았던 시대는 아브라함 시대였다.");
comment.push("▸욥기의 문학적 쟝르는 희곡에 가깝다.");
comment.push("▸욥기의 저자는 밝혀지지 않았다.");
comment.push("▸기록된 연대는 바벨론 포로기간으로 본다.");
comment.push("▸욥이 당했던 시험은 크게 세 가지였다.");
comment.push("  1. 재물과 자녀들을 잃게 되는 시험");
comment.push("  2. 건강을 잃고 병들어 고통 받는 시험");
comment.push("  3. 친구들로부터 정죄 받는 시험이었다");