var bible_chapter= [];

bible_chapter.push('1 말씀의성육신');
bible_chapter.push('2 가나의 혼인 잔치');
bible_chapter.push('3 니고데모의 질문');
bible_chapter.push('4 사마리아여인 과의 대화');
bible_chapter.push('5 예수님을 증거한 성경 ');
bible_chapter.push('6 오병이어 너희가 나를 찾는 까닭');
bible_chapter.push('7 생수의 강 강(江)');
bible_chapter.push('8 간음한 여인');
bible_chapter.push('9 실로암 연못');
bible_chapter.push('10 선한 목자');
bible_chapter.push('11 다시 살아난  나사로');
bible_chapter.push('12 향유로 예수님의발을 씻기는마리아');
bible_chapter.push('13 제자들의 발을 씻기신예수님');
bible_chapter.push('14 마음에 근심하지말라');
bible_chapter.push('15 포도나무와 가지의 비유');
bible_chapter.push('16 보혜사성령 강림예언');
bible_chapter.push('17 예수님의 기도');
bible_chapter.push('18 예수님의 붙잡힘');
bible_chapter.push('19 나사렛예수 유대인의왕');
bible_chapter.push('20 도마의 의심');
bible_chapter.push('21 내 어린양을 먹이라');

var comment= [];
comment.push('<요한복음에 나오는 기사>');
comment.push('1.갈릴리 가나의 혼인잔치');
comment.push('2.니고데모가 찾아 온 사건');
comment.push('-마태, 베드로 다 누워 자러 갔다. 그래서 다른 복음서에 안나온다.');
comment.push('3.베데스다 못가의 병자를 고치다');
comment.push('4.나는 선한 목자다');
comment.push('5.죽은 나사로를 살리다');
comment.push('6.포도나무 비유');
comment.push('7.대제사장의 기도');
comment.push('8.도마의 신앙고백');
comment.push('9.베드로의 사랑고백');
comment.push('10.위에서 오는 그리스도');
comment.push('11.사마리아 우물가의 여인');
comment.push('12.죄 없는 자가 먼저 돌로 치라');
comment.push('13.보혜사 성령에 관한 말씀');
comment.push('14.새 계명을 수여하시는 말씀');
comment.push('15.한 알의 밀');
comment.push('16.제자들의 발을 씻으신 사건');
comment.push('17.나다나엘의 소명');