var bible_chapter = [];
bible_chapter.push("1 여호수아 취임");
bible_chapter.push("2 여리고 라합과두 정탐꾼");
bible_chapter.push("3 요단강이갈라짐");
bible_chapter.push("4 요단도하기념비");
bible_chapter.push("5 출애굽 후 첫 할례,세번째유월절");
bible_chapter.push("6 여리고함락");
bible_chapter.push("7 아이성함락실패");
bible_chapter.push("8 아이성함락성공");
bible_chapter.push("9 기브온과우호 조약");
bible_chapter.push("10 태양과 달멈춤");
bible_chapter.push("11 북부연합국멸절");
bible_chapter.push("12 여호수아에게 패배한 31왕");
bible_chapter.push("13 요단강동편토지 분배");
bible_chapter.push("14 갈렙의 기업");
bible_chapter.push("15 유다의 기업");
bible_chapter.push("16 에브라임  의 기업");
bible_chapter.push("17 므낫세의기업");
bible_chapter.push("18 베냐민의기업(실로에회막)");
bible_chapter.push("19 시,스,잇,아,납,단,여호수아기업");
bible_chapter.push("20 도피성 6개");
bible_chapter.push("21 레위지파기업");
bible_chapter.push("22 요단강동쪽지파의 귀환");
bible_chapter.push("23 여호수아의고별설교");
bible_chapter.push("24 여호수아죽음");

var comment = [];
comment.push("1.여호수아 취임");
comment.push("2.요단강 도하");
comment.push("3.가나안 중부전투");
comment.push("4.가나안 남부전투");
comment.push("5.가나안 북부전투");
comment.push("6.가나안 전투결산");
comment.push("7.토지 분배와 여호수아의 고별사");
comment.push("<img src='./img/joshua_01.png'>");
