var bible_chapter = [];
bible_chapter.push("1 여호수아 사망");
bible_chapter.push("2 이스라엘의 우상숭배");
bible_chapter.push("3 옷니엘,에훗, 삼갈");
bible_chapter.push("4 야엘이시스라 죽임");
bible_chapter.push("5 드보라와 바락의 노래");
bible_chapter.push("6 기드온의 표적");
bible_chapter.push("7 기드온의 300용사");
bible_chapter.push("8 기드온의 40년 정치");
bible_chapter.push("9 아비멜렉의 죽음");
bible_chapter.push("10 돌라,야일");
bible_chapter.push("11 입다의서원");
bible_chapter.push("12 입산,엘론압돈");
bible_chapter.push("13 삼손의출생");
bible_chapter.push("14 사자를 죽인삼손");
bible_chapter.push("15 나귀턱뼈로승리");
bible_chapter.push("16 머리잘린삼손");
bible_chapter.push("17 미가의 신상");
bible_chapter.push("18 단 지파의 신상 섬김");
bible_chapter.push("19 욕을 당한 레위인의 첩");
bible_chapter.push("20 이스라엘의내전");
bible_chapter.push("21 [결론]왕이없는이스라엘");
var comment = [];
comment.push("사사기의 개요 - [구약 시대 종교암흑기 원인]");
comment.push("1.토지 분배로 힘이 분산");
comment.push("2.그 땅 거민을 쫓아내지 못함");
comment.push("3.그 땅 거민과 동거하다가 동화됨");
comment.push("4.구원역사의 목격자들의 별세");
comment.push("5.성경을 통독하지 않음");
comment.push("6.여호수아가 후계자를 세우지 못함");
comment.push("<타락의 역사>");
comment.push("1.온 세상을 위하여 이스라엘을 선택");
comment.push("2.그 중에서 레위지파를 선택");
comment.push("3.레위 지파 중에서 아론 자손을 선택");
comment.push("4.그 다음은 사사를 세웠다");
comment.push("5.사사가 타락하자 나실인을 세웠다");
comment.push("6.나실인들 후에는 왕을 세웠다.");
comment.push("7.왕들도 타락하자 예언자를 보냈다");
comment.push("8.예언자들이 타락하자 독생자를 보내셨다");
comment.push("<img src='./img/Judges_01.png'>");
comment.push("<img src='./img/Judges_02.png'>");