var bible_chapter= [];

bible_chapter.push('1 세례요한의출생');
bible_chapter.push('2 말구유의예수님 탄생목자의 경배');
bible_chapter.push('3 세례요한의설교');
bible_chapter.push('4 나사렛 회당설교');
bible_chapter.push('5 깊은곳에그물을내려고기를잡으라');
bible_chapter.push('6 주라그러면넘치도록주리라');
bible_chapter.push('7 한 여인이향유를 부은사건');
bible_chapter.push('8 등불의 비유');
bible_chapter.push('9 여우도굴이 있고');
bible_chapter.push('10 칠십인 제자파송');
bible_chapter.push('11 강청함을인하여 주는떡 세 덩이');
bible_chapter.push('12 어리석은부자의 비유');
bible_chapter.push('13 예루살렘에대한 탄식');
bible_chapter.push('14 소금의 교훈');
bible_chapter.push('15 잃은 양의비유');
bible_chapter.push('16 부자와 나사로 ');
bible_chapter.push('17 뽕나무를옮기는 믿음');
bible_chapter.push('18 하나님의나라를위해모든것버린자');
bible_chapter.push('19 뽕나무위에 올라간삭개오');
bible_chapter.push('20 서기관을삼가라');
bible_chapter.push('21 과부의두 렙돈');
bible_chapter.push('22 최후의 만찬');
bible_chapter.push('23 십자가상의두 강도 ');
bible_chapter.push('24 부활,엠마오로가는두 제자');

var comment= [];
comment.push('1.세례요한의 탄생기사를 기록한다.');
comment.push('2.세례요한이 나타날 때 정치적 배경 기록한다.');
comment.push('3.호적하기 위해서 베들레헴에 갔다고 기록한다.');
comment.push('4.목자들의 경배를 기록하고 있다.');
comment.push('5.예수님의 할례사건을 기록한다.');
comment.push('6.예루살렘 성전의 제사를 기록한다.');
comment.push('7.예수님의 어린시절 이야기를 쓰고 있다.');
comment.push('8.아브라함 이상의 족보를 근원까지 기록한다.');
comment.push('9.세례요한과 세리, 군인들의 대화를 기록한다.');
comment.push('10.나사렛 회당에서 처음 설교를 기록한다.');
comment.push('11.칠십인 제자 이야기를 찾아냈다.');
comment.push('12.선한 사마리아인 이야기를 쓰고 있다.');
comment.push('13.말씀을 듣고 있는 마리아를 그리고 있다.');
comment.push('14.많은 여인들을 챙기고 이름들을 밝힌다.');
comment.push('15.사마리아인 세리 창녀 가난한자 병든 자를 챙긴다.');
comment.push('16.탕자의 비유를 찾아내어 기록 했다.');
comment.push('17.부자와 나사로의 삶과 죽음을 다루고 있다.');
comment.push('18.빌라도가 제물에 피 섞은 사건을 다룬다.');
comment.push('19.불의한 청지기 비유도 누가가 찾았다.');
comment.push('20.감사하려고 돌아온 사마리아 사람');
comment.push('21.불의한 재판관과 번거롭게 하는 과부이야기');
comment.push('22.뽕나무에 올라갔던 삭개오 이야기');
comment.push('23.부자의 헌금과 과부의 두 렙돈 헌금');
comment.push('24.바리새인과 세리의 기도');
comment.push('25.헤롯왕의 조롱을 당하신 메시야');
comment.push('26.포도원 가운데 심겨진 무화과나무');
comment.push('27.엠마오로 가는 두 제자 이야기');
comment.push('28.부활하신 주님의 승천기사');
comment.push('29.천사, 마리아, 사가랴, 엘리사벳, 시몬의 찬양');
comment.push('30.고창병 환자를 고치신 기사');