var bible_chapter= [];
bible_chapter.push("1 세례요한등장");
bible_chapter.push("2 밀이삭사건(안식일논쟁)");
bible_chapter.push("3 열두제자를세우신이유");
bible_chapter.push("4 씨 뿌리는자의 비유");
bible_chapter.push("5 야이로의딸을 살리심");
bible_chapter.push("6 고향에서환영받지못한예수님");
bible_chapter.push("7 입술로는존경하되마음은내게서멀다");
bible_chapter.push("8 7병2어 자기십자가를지고 좇을것");
bible_chapter.push("9 변화산 사건");
bible_chapter.push("10 하나님이짝지어주신것사람이못나눔");
bible_chapter.push("11 Jer입성만민의기도하는 집");
bible_chapter.push("12 모퉁이의 머릿돌");
bible_chapter.push("13 천사도 알수없는 종말");
bible_chapter.push("14 베드로의부인(否認)");
bible_chapter.push("15 십자기의죽음찢어진 휘장");
bible_chapter.push("16 빈 무덤복음전파의지상 명령");

var comment= [];
comment.push("<마가복음 개요>");
comment.push("1.마가는 바울과 바나바의 수행원으로 섬겼다.");
comment.push("2.마가는 베드로의 수행원으로 섬겼다.");
comment.push("3.마가가 전한 복음은 베드로가 전한 복음 이었다.");
comment.push("4.따라서 마가복음은 베드로 복음이라 할 수 있다.");
comment.push("5.마가복음서는 다른 복음서의기초가 되었다.");
comment.push("6.세례요한의 사역과 그리스도의 준비");
comment.push("7.제자들을 부르시는 예수님");
comment.push("8.천국에 관한 비유들");
comment.push("9.병자들과 귀신들린 자들을 고치심");
comment.push("10.7병2어로 사천 명을 먹인 사건");
comment.push("11.베드로의 신앙고백");
comment.push("12.변화산에서 보이신 영광");

comment.push("13.예루살렘으로 올라가시는 길");
comment.push("14.수난에 대한 예고");
comment.push("15.예루살렘 입성");
comment.push("16.성전 숙청");
comment.push("17.마지막 한 주간의 교훈");
comment.push("18.크고 첫째가는 교훈");
comment.push("19.마가복음의 종말론");
comment.push("20.베다니 문둥이 시몬의 집 방문");
comment.push("21.최후의 만찬");
comment.push("22.그리스도의 수난과 부활");
comment.push("23.승천");
