var bible_chapter= [];
bible_chapter.push("1 아기예수탄생과 족보");
bible_chapter.push("2 동방박사에게 경배받으신 예수");
bible_chapter.push("3 세례요한에게세례받으신예수");
bible_chapter.push("4 사십일금식과 사단의 시험");
bible_chapter.push("5 산상수훈팔복천국시민차격");
bible_chapter.push("6 산상수훈중언부언마라주기도문");
bible_chapter.push("7 산상수훈반석위에지은 집");
bible_chapter.push("8 이적기사문둥병자고치심");
bible_chapter.push("9 이적기사새 포도주는새 부대에");
bible_chapter.push("10 12제자 파송및 설교");
bible_chapter.push("11 세례요한질문에 대한예수님 답변");
bible_chapter.push("12 안식일에구덩이에빠진양을 구해냄");
bible_chapter.push("13 천국비유값진 진주의비유");
bible_chapter.push("14 오병이어");
bible_chapter.push("15 개들도 떡부스러기먹음");
bible_chapter.push("16 천국열쇠베드로의신앙 고백");
bible_chapter.push("17 변화산 사건");
bible_chapter.push("18 두세사람이내이름으로모인곳에");
bible_chapter.push("19 부자청년");
bible_chapter.push("20 천국비유포도원품꾼의비유");
bible_chapter.push("21 예루살렘입성(종려주일)");
bible_chapter.push("22 두 계명(화요일)");
bible_chapter.push("23 서기관과바리새인책망(화요일)");
bible_chapter.push("24 Jer멸망예언(화요일)");
bible_chapter.push("25 열 처녀양과 염소달란트비유");
bible_chapter.push("26 겟세마네동산 기도(목요일)");
bible_chapter.push("27 십자가 죽음(금요일)");
bible_chapter.push("28 부 활(주일)");

var comment= [];
comment.push("<마태복음의 개요>");
comment.push("1.아브라함과 다윗의 자손 예수 그리스도");
comment.push("2.다윗의 동네에서 나신 메시야");
comment.push("3.유대인의 왕으로 임하신 메시야");
comment.push("4.구약성경의 예언을 성취하신 메시야");
comment.push("5.죄인을 불러 회개케 하시는 메시야");
comment.push("6.진리로 가르치시는 메시야");
comment.push("7.죄에서 구원하시는 메시야");
comment.push("8.귀신의 권세를 이기시는 메시야");
comment.push("9.모든 질병에서 구원하시는 메시야");
comment.push("10.우리의 양식을 책임지시는 메시야");
comment.push("11.안식일의 주인이 되시는 메시야");
comment.push("12.비유로 가르치는 메시야");
comment.push("13.변화산에서 변모하시는 메시야");
comment.push("14.유대인의 왕으로 입성하시는 메시야");
comment.push("15.성전을 숙청하시는 메시야");
comment.push("16.위선자들을 질책하시는 메시야");
comment.push("17.예루살렘의 멸망과 종말을 가르치시는 메시야 [마24-25장]");
comment.push("18.수난을 예고하시는 메시야");
comment.push("19.최후의 만찬을 나누시는 메시야");
comment.push("20.십자가에 달리시는 메시야");
comment.push("21.죽음을 이기시고 부활하시는 메시야");
comment.push("22.최후의 유언을 위탁하시는 메시야");