var bible_chapter = [];
bible_chapter.push("1 니느웨 멸망 예언");
bible_chapter.push("2 니느웨 멸망한 후의 참상");
bible_chapter.push("3 니느웨 멸망 원인");

var comment = [];
comment.push("<나훔(위로) 선지자의 묵시>");
comment.push("▪나훔은 니느웨의 멸망을 예언했다.");
comment.push("▪여호와는 투기하시는 하나님이다.");
comment.push("▪여호와는 보복하시는 하나님이다.");
comment.push("▪여호와는 노하기를 더디 하신다.");
comment.push("▪그러나 끝날에는 반드시 심판하신다.");
comment.push("▪회개할 줄 모르는 앗수르, 음란과 마술로 만국을 미혹하던 니느웨는 완전히 멸망한다.");
comment.push("▪나훔은 니느웨에 대한 혹독한 묵시를 보았다.");
comment.push("▪나훔의 예언은 BC.612년에 성취되었다.");
comment.push("<하나님의 모습>");
comment.push("창세기를 통해 나타난 하나님은 창조의 하나님. 물론 홍수로 심판하는 모습도 보임.");
comment.push("출애굽기는 구원하시는 하나님");
comment.push("레위기는 언약하시는 하나님");
comment.push("민수기는 훈련시키시는 하나님");
comment.push("신명기는 설명해 주시는 하나님");
comment.push("여호수아-약속을 지키시는 하나님 ");
comment.push("사사기-재판하시는 하나님 ");
comment.push("룻기-속량하시는(우리의 기업무를자)의 하나님 ");
comment.push("사무엘상-기도를 들으시는 하나님 ");
comment.push("사무엘하-감찰하시는 하나님 ");
comment.push("열왕기상-다스리시는 하나님 ");
comment.push("열왕기하-예언자를 보내시는 하나님 ");
comment.push("역대상-기억하게 하시는 하나님 ");
comment.push("역대하-회복하게 하시는 하나님 ");
comment.push("에스라-도우시는 하나님 ");
comment.push("느헤미야-위로하시는 하나님 ");
comment.push("에스더-보복하시는 하나님 ");
comment.push("욥기-시험하시는 하나님 ");
comment.push("시편-찬양 받으실 하나님 ");
comment.push("잠언-지혜로우신 (지혜주시는)하나님 ");
comment.push("전도서-인생의 허물을 보여주시는 하나님 ");
comment.push("아가-사랑의 근원과 원형을 보여 주시는 하나님 ");
comment.push("이사야-구원하시는 하나님 ");
comment.push("에레미야-심판하시는 하나님 ");
comment.push("에레미야애가-울고 있는 하나님 ");
comment.push("에스겔-진노하시는 하나님 ");
comment.push("다니엘-포기하지 않으시는 하나님 ");
comment.push("호세야-사랑과 질투의 하나님 ");
comment.push("요엘-권면하시는 하나님 ");
comment.push("아모스-공평과 정의의 하나님 ");
comment.push("오바댜-도덕적으로 심판하시는 하나님 ");
comment.push("요나-이방인까지 아끼시는 하나님 ");
comment.push("미가-경제정의, 사회정의를 부르짖는 하나님 ");
comment.push("나훔-(앗수르)보복하시는 하나님, (이스라엘)위로하시는 하나님, ");
comment.push("하박국-응답하시는 하나님 ");
comment.push("스바냐-우주적 대 심판 때에 숨겨주시는 하나님 ");
comment.push("학개-책망하시고 격려하시는 하나님 ");
comment.push("스가랴-기억하시는 하나님 ");
comment.push("말라기-기가 막혀 말을 못하시는 하나님 ");
comment.push("마태복음-유대인의 왕으로 오시는 하나님 ");
comment.push("마가복음-섬기러 오시는 하나님 ");
comment.push("누가복음-천하 만민의 하나님 ");
comment.push("요한복음-초월자 이신 하나님 ");
comment.push("사도행전-성령으로 임하시는 하나님 ");
comment.push("로마서-믿음을 의로 여기시는 하나님 ");
comment.push("고린도전서-하나 되게 하시고 은사 주시는 하나님 ");
comment.push("고린도후서-책망하시고 위로하시는 하나님 ");
comment.push("갈라디아서-자유케 하시고 섬기시게 하시는 하나님 ");
comment.push("에베소서-예정하시고 선택하시는 하나님 ");
comment.push("빌립보-기쁨을 주시는 하나님 ");
comment.push("골로새서-그리스도 안에 있는 하나님 ");
comment.push("데살로니가전서-다시 오실 하나님 ");
comment.push("데살로니가후서-길이 참으시는 하나님 ");
comment.push("디모데전서-교회를 세우시고 직책을 맡기시는 하나님 ");
comment.push("디모데후서-면류관을 예비하시는 하나님 ");
comment.push("디도서-교회를 거룩하게 하시는 하나님 ");
comment.push("빌레몬-변화시키시는 하나님 ");
comment.push("히브리서-모든 것보다 우월하시는 하나님 ");
comment.push("야고보서-행위를 달아 보시는 하나님 ");
comment.push("베드로전서-우리의 소망이 되시는 하나님 ");
comment.push("베드로후서-우리를 자랑하게 하시는 하나님 ");
comment.push("요한1서-사랑 안에 거하시는 하나님 ");
comment.push("요한2서-이단을 경계하시는 하나님 ");
comment.push("요한3서-나그네를 섬기라 하시는 하나님 ");
comment.push("유다서-이단을 심판하시는 하나님 ");
comment.push("요한계시록-교회를 지키시는 하나님,교회를 거룩하게 하시는 하나님,교회를 깨우시는 하나님, 세상을 심판하실 하나님 최후의 심판에서 승리하시고, 크고 흰 보좌에서 온 천하 만민을 천국과 지옥을가게 하시는하나님 ");